$(document).ready(function(){
	   //alert("If you found any bug try to run the code again.")
		setTimeout(function(){
			$(".hf").hide();
		},10);
		$(".items").html("<p><b>🍓🍌🍋🍒🍅🍞🍗🌰🍖👕👓👖👗👚👞👟👠👡👒🍎🍏🍉🍈🍐🍊🍅🍣🍤🍔🍟🍕🍳🍲🍱🍝🍠🍧🍨</b></p>");
		$(".truck").click(function(){
		$(".items").animate({
		width:'50px',
		left:'10px'
		},1000);
		$(".n1").animate({
		top:'600px'
		},200);
		$(".n2").animate({
		top:'600px'
		},300);
		$(".n3").animate({
		top:'600px'
		},400);
		$(".engine").delay(750).animate({
		left:'200px'
		},500);
		$(".hf").fadeIn(2800).show();
		});
		setTimeout(function(){
		$(".truck").hide();
		},3000);
		});
